apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-2
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       8082;
          server_name  localhost;
          location / {
            root   html;
            index  index.html index.htm;
        }
      }
    }